# Site wide configuration

title:            Pineapples and Python
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Natalie Retamar
  avatar: bio-photo.jpg
  bio: "Friendly and curious. Sales pro turned data nerd. Craft nut. Really like Python and pineapples."
  email: Natalie.Retamar@gmail.com
  disqus-shortname:
  twitter: '@da_CasObserver'
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: 'https://github.com/natalieretamar'
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: "https://www.linkedin.com/in/natalieretamar"
  xing: #username
  instagram: "@nyc_nat"
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
